name: "audi"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  audi:
    name: "audi"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
    - id: crawl
      uses: ./.github/workflows/retrieve-upload
      with:
        script-name: "audi"
