name: "Batch of approved scripts"

on:
  workflow_dispatch:

  schedule:
  - cron: "30 20 * * *"

defaults:
  run:
    working-directory: ./scripts

jobs:
  byd:
    name: "byd"
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repository to the runner"
      uses: actions/checkout@v4

    - name: "Retrieve data"
      run: |
        python byd.py

    - name: "Upload data"
      uses: actions/upload-artifact@v4
      with: 
        name: byd
        path: ${{ github.workspace }}/output/*.csv
  
  audi:
    name: "audi"
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repository to the runner"
      uses: actions/checkout@v4

    - name: "Retrieve data"
      run: |
        python audi.py

    - name: "Upload data"
      uses: actions/upload-artifact@v4
      with: 
        name: audi
        path: ${{ github.workspace }}/output/*.csv
    
  benz:
    name: "benz"
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repository to the runner"
      uses: actions/checkout@v4

    - name: "Retrieve data"
      run: |
        python benz.py

    - name: "Upload data"
      uses: actions/upload-artifact@v4
      with:
        name: benz
        path: ${{ github.workspace }}/output/*.csv

  bridgestone:
    name: "bridgestone"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repository to the runner"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5.6.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.13

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: "Setup Chrome & ChromeDriver"
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          # The Google Chrome/Chromium version to install and use.
          chrome-version: 136
          # Install the compatible version of ChromeDriver with the installed Google Chrome/Chromium.
          install-chromedriver: true

      - name: "Retrieve data"
        run: |
          python bridgestone.py

      - name: "Upload data"
        uses: actions/upload-artifact@v4
        with:
          name: bridgestone
          path: ${{ github.workspace }}/output/*.csv

  michelin:
    name: "michelin"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repository to the runner"
        uses: actions/checkout@v4

      - name: "Retrieve data"
        run: |
          python michelin.py

      - name: "Upload data"
        uses: actions/upload-artifact@v4
        with:
          name: michelin
          path: ${{ github.workspace }}/output/*.csv

  continental:
    name: "continental"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repository to the runner"
        uses: actions/checkout@v4

      - name: "Retrieve data"
        run: |
          python continental.py

      - name: "Upload data"
        uses: actions/upload-artifact@v4
        with:
          name: continental
          path: ${{ github.workspace }}/output/*.csv

  tesla:
    name: "tesla"
    runs-on: windows-latest

    steps:
      - name: "Check out the repository to the runner"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5 # 建议使用 v5 的较新稳定版
        with:
          python-version: '3.11' # 建议使用一个广泛支持的稳定版本，如 3.11，除非您确实需要 3.13 的特定功能

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: "Setup Chrome & ChromeDriver"
        uses: browser-actions/setup-chrome@v1 # 版本号通常是 v1.x.x，请确认最新稳定版
        with:
          chrome-version: 'stable' # 或者指定一个版本如 '114'， 'stable' 通常能获取最新稳定版
          install-chromedriver: true # 对于 browser-actions/setup-chrome@v1，chromedriver 通常会自动安装

      - name: "Retrieve data"
        run: python tesla.py
        env: # <--- 添加此部分
          PYTHONIOENCODING: utf-8 # <--- 添加此行

      - name: "Upload data"
        uses: actions/upload-artifact@v4
        with:
          name: tesla
          # 路径应相对于 working-directory，如果脚本输出到 output/tesla.csv，且 working-directory 是项目根目录，则此路径正确
          path: ${{ github.workspace }}/output/*.csv # 确保这里的路径与您脚本中 OUTPUT_PATH 的最终文件名一致

  maserati:
    name: "maserati"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repository to the runner"
        uses: actions/checkout@v4

      - name: "Retrieve data"
        run: |
          python Maserati.py

      - name: "Upload data"
        uses: actions/upload-artifact@v4
        with:
          name: maserati
          path: ${{ github.workspace }}/output/*.csv

  porsche:
    name: "porsche"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repository to the runner"
        uses: actions/checkout@v4

      - name: "Retrieve data"
        run: |
          python porsche.py

      - name: "Upload data"
        uses: actions/upload-artifact@v4
        with:
          name: porsche
          path: ${{ github.workspace }}/output/*.csv
