name: "Batch of approved scripts"

on:
  workflow_dispatch:

  schedule:
  - cron: "30 20 * * *"

defaults:
  run:
    working-directory: ./scripts

jobs:
  byd:
    uses: ./.github/workflows/byd.yml
  
  audi:
    uses: ./.github/workflows/audi.yml

  benz:
    uses: ./.github/workflows/benz.yml

  bridgestone:
    uses: ./.github/workflows/bridgestone.yml

  michelin:
    uses: ./.github/workflows/michelin.yml

  continental:
    uses: ./.github/workflows/continental.yml
