name: "bridgestone"

env:
  brand: "bridgestone"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.13

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.3
      with:
        # The Google Chrome/Chromium version to install and use.
        chrome-version: 136
        # Install the compatible version of ChromeDriver with the installed Google Chrome/Chromium.
        install-chromedriver: true

    - name: "Retrieve & upload data"
      uses: ./.github/workflows/retrieve-upload
      with:
        script-name: ${{ env.brand }}
