name: "Run spiders & generate CSV results"

on:
  workflow_dispatch:

  schedule:
  - cron: "30 20 * * *"

defaults:
  run:
    working-directory: ./scripts

jobs:
  byd:
    name: "byd"
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: "Retrieve data to CSV"
      run: |
        python byd.py

    - name: "Upload CSV"
      uses: actions/upload-artifact@v4
      with: 
        name: byd
        path: /output/*.csv
  
  audi:
    name: "audi"
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: "Retrieve data to CSV"
      run: |
        python audi.py

    - name: "Upload CSV"
      uses: actions/upload-artifact@v4
      with: 
        name: audi
        path: /output/*.csv
    
  benz:
    name: "benz"
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: "Retrieve data to CSV"
      run: |
        python benz.py

    - name: "Upload CSV"
      uses: actions/upload-artifact@v4
      with: 
        name: benz
        path: /output/*.csv
