name: "Run tesla"

on:
  workflow_dispatch:

jobs:
  tesla:
    name: "tesla"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium.webdriver.common.devtools.v134
        sudo apt-get update
        sudo apt-get install -y chromium-browser  # 安装 Chromium 浏览器

    - name: "Retrieve data to CSV"
      run: |
        python scripts/tesla.py

    - name: "Upload CSV"
      uses: actions/upload-artifact@v4
      with:
        name: csv-output
        path: output/tesla.csv
