name: "yokohoma"

env:
  brand: "yokohoma"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    - name: "Retrieve & upload data"
      uses: ./.github/workflows/retrieve-upload
      with:
        script-name: ${{ env.brand }}